function loadQuestions01() {
  return [
    {
      num: 1,
      tropic: '1. Network Fundamentals',
      subTropic: '1.1 Conceitos de rede',
      question:
        'Uma empresa conecta computadores dentro de um único prédio utilizando switches Ethernet. Que tipo de rede está sendo utilizada?',
      options: ['WAN', 'LAN', 'MAN', 'PAN'],
      answer: 'LAN',
      clue: 'Escopo local, dentro de prédio ou campus pequeno.',
    },
    {
      num: 2,
      tropic: '1. Network Fundamentals',
      subTropic: '1.1 Conceitos de rede',
      question:
        'Uma operadora conecta filiais de uma empresa em diferentes estados do país utilizando links MPLS. Esse cenário caracteriza qual tipo de rede?',
      options: ['LAN', 'PAN', 'WAN', 'MAN'],
      answer: 'WAN',
      clue: 'Abrange grandes distâncias geográficas.',
    },
    {
      num: 3,
      tropic: '1. Network Fundamentals',
      subTropic: '1.1 Conceitos de rede',
      question:
        'Uma universidade conecta seus prédios distribuídos pela cidade utilizando fibra óptica própria. Esse cenário é melhor classificado como:',
      options: ['PAN', 'LAN', 'MAN', 'WAN'],
      answer: 'MAN',
      clue: 'Abrange uma área metropolitana.',
    },
    {
      num: 4,
      tropic: '1. Network Fundamentals',
      subTropic: '1.1 Conceitos de rede',
      question:
        'Um usuário conecta seu notebook ao smartphone via Bluetooth para compartilhar internet. Que tipo de rede é essa?',
      options: ['WAN', 'LAN', 'PAN', 'MAN'],
      answer: 'PAN',
      clue: 'Rede pessoal de curto alcance.',
    },
    {
      num: 5,
      tropic: '1. Network Fundamentals',
      subTropic: '1.1 Conceitos de rede',
      question: 'Qual característica é mais associada a uma WAN?',
      options: [
        'Alta taxa de transmissão e baixa latência garantida',
        'Escopo limitado a um único edifício',
        'Interconexão de redes locais através de provedores',
        'Uso exclusivo de Ethernet',
      ],
      answer: 'Interconexão de redes locais através de provedores',
      clue: 'WAN normalmente depende de operadoras.',
    },
    {
      num: 6,
      tropic: '1. Network Fundamentals',
      subTropic: '1.1 Conceitos de rede',
      question: 'Qual tecnologia é mais comum em uma LAN corporativa?',
      options: ['Bluetooth', 'Ethernet', 'MPLS', 'LTE'],
      answer: 'Ethernet',
      clue: 'LAN tradicionalmente usa Ethernet.',
    },
    {
      num: 7,
      tropic: '1. Network Fundamentals',
      subTropic: '1.1 Conceitos de rede',
      question: 'Qual é a principal diferença entre LAN e WAN?',
      options: [
        'LAN usa IP e WAN não usa',
        'WAN cobre maiores distâncias geográficas',
        'LAN é pública e WAN é privada',
        'WAN usa apenas fibra óptica',
      ],
      answer: 'WAN cobre maiores distâncias geográficas',
      clue: 'A principal diferença é o alcance.',
    },
    {
      num: 8,
      tropic: '1. Network Fundamentals',
      subTropic: '1.1 Conceitos de rede',
      question:
        'Uma empresa possui matriz e três filiais na mesma cidade conectadas por links dedicados de fibra contratados de uma operadora. Isso é classificado como:',
      options: ['PAN', 'LAN', 'MAN', 'VPN doméstica'],
      answer: 'MAN',
      clue: 'Conexão dentro de uma área metropolitana.',
    },
    {
      num: 9,
      tropic: '1. Network Fundamentals',
      subTropic: '1.1 Conceitos de rede',
      question: 'Qual cenário representa melhor uma PAN?',
      options: [
        'Conectar matriz e filial em estados diferentes',
        'Rede doméstica com vários dispositivos',
        'Fone Bluetooth conectado ao celular',
        'Campus universitário com vários prédios',
      ],
      answer: 'Fone Bluetooth conectado ao celular',
      clue: 'PAN é rede pessoal de curtíssimo alcance.',
    },
    {
      num: 10,
      tropic: '1. Network Fundamentals',
      subTropic: '1.1 Conceitos de rede',
      question:
        'Qual das opções abaixo NÃO é uma característica típica de uma LAN?',
      options: [
        'Alta velocidade',
        'Baixa latência',
        'Grande alcance geográfico',
        'Controle administrativo local',
      ],
      answer: 'Grande alcance geográfico',
      clue: 'Grande alcance é característica de WAN.',
    },

    {
      num: 11,
      tropic: '1. Network Fundamentals',
      subTropic: '1.1 Conceitos de rede',
      question:
        'Uma operadora fornece conexão entre países para uma multinacional. Esse tipo de rede é classificado como:',
      options: ['LAN', 'MAN', 'WAN', 'PAN'],
      answer: 'WAN',
      clue: 'Abrange países ou continentes.',
    },
    {
      num: 12,
      tropic: '1. Network Fundamentals',
      subTropic: '1.1 Conceitos de rede',
      question:
        'Qual tipo de rede normalmente pertence e é gerenciada por uma única organização dentro de um prédio?',
      options: ['WAN', 'LAN', 'MAN', 'PAN'],
      answer: 'LAN',
      clue: 'LAN geralmente é privada e local.',
    },
    {
      num: 13,
      tropic: '1. Network Fundamentals',
      subTropic: '1.1 Conceitos de rede',
      question: 'Qual rede é mais provável apresentar maior latência?',
      options: ['PAN', 'LAN', 'WAN', 'Rede interna de laboratório'],
      answer: 'WAN',
      clue: 'Maior distância tende a maior latência.',
    },
    {
      num: 14,
      tropic: '1. Network Fundamentals',
      subTropic: '1.1 Conceitos de rede',
      question: 'Qual tecnologia é mais associada a uma PAN?',
      options: ['Ethernet', 'Bluetooth', 'MPLS', 'Metro Ethernet'],
      answer: 'Bluetooth',
      clue: 'Bluetooth é típico de rede pessoal.',
    },
    {
      num: 15,
      tropic: '1. Network Fundamentals',
      subTropic: '1.1 Conceitos de rede',
      question:
        'Um conjunto de prédios interligados dentro de um campus empresarial caracteriza:',
      options: ['PAN', 'LAN estendida', 'WAN global', 'Rede pública de ISP'],
      answer: 'LAN estendida',
      clue: 'Ainda é LAN, mesmo com vários prédios próximos.',
    },

    {
      num: 16,
      tropic: '1. Network Fundamentals',
      subTropic: '1.1 Conceitos de rede',
      question:
        'Qual rede normalmente depende de um provedor de serviços para interligação?',
      options: ['LAN', 'PAN', 'WAN', 'Rede interna de laboratório'],
      answer: 'WAN',
      clue: 'WAN geralmente envolve ISP.',
    },
    {
      num: 17,
      tropic: '1. Network Fundamentals',
      subTropic: '1.1 Conceitos de rede',
      question: 'Qual das opções descreve melhor uma MAN?',
      options: [
        'Rede pessoal entre dispositivos',
        'Rede que cobre uma cidade',
        'Rede de um único escritório',
        'Rede doméstica Wi-Fi',
      ],
      answer: 'Rede que cobre uma cidade',
      clue: 'MAN é metropolitana.',
    },
    {
      num: 18,
      tropic: '1. Network Fundamentals',
      subTropic: '1.1 Conceitos de rede',
      question:
        'Uma rede doméstica conectando computadores, impressora e TV é classificada como:',
      options: ['WAN', 'LAN', 'MAN', 'Backbone da internet'],
      answer: 'LAN',
      clue: 'Rede local residencial ainda é LAN.',
    },
    {
      num: 19,
      tropic: '1. Network Fundamentals',
      subTropic: '1.1 Conceitos de rede',
      question:
        'Qual tipo de rede normalmente apresenta menor custo por link interno?',
      options: [
        'WAN internacional',
        'LAN interna',
        'MAN contratada',
        'Link satelital global',
      ],
      answer: 'LAN interna',
      clue: 'Infraestrutura própria e local.',
    },
    {
      num: 20,
      tropic: '1. Network Fundamentals',
      subTropic: '1.1 Conceitos de rede',
      question: 'Qual alternativa melhor diferencia MAN de WAN?',
      options: [
        'MAN usa IP e WAN não',
        'WAN cobre áreas maiores que MAN',
        'MAN é doméstica e WAN é empresarial',
        'WAN é sempre sem fio',
      ],
      answer: 'WAN cobre áreas maiores que MAN',
      clue: 'Escala geográfica é o fator chave.',
    },

    {
      num: 21,
      tropic: '1. Network Fundamentals',
      subTropic: '1.1 Conceitos de rede',
      question:
        'Um smartwatch conectado ao celular via Bluetooth é exemplo de:',
      options: ['LAN', 'MAN', 'PAN', 'WAN'],
      answer: 'PAN',
      clue: 'Dispositivos pessoais de curto alcance.',
    },
    {
      num: 22,
      tropic: '1. Network Fundamentals',
      subTropic: '1.1 Conceitos de rede',
      question:
        'Uma empresa conecta escritórios em diferentes continentes. Isso é classificado como:',
      options: ['LAN', 'MAN', 'WAN', 'PAN'],
      answer: 'WAN',
      clue: 'Escala continental é WAN.',
    },
    {
      num: 23,
      tropic: '1. Network Fundamentals',
      subTropic: '1.1 Conceitos de rede',
      question:
        'Qual rede normalmente utiliza switches como principal dispositivo de interconexão?',
      options: ['LAN', 'WAN', 'PAN', 'Internet global'],
      answer: 'LAN',
      clue: 'Switch é típico de LAN.',
    },
    {
      num: 24,
      tropic: '1. Network Fundamentals',
      subTropic: '1.1 Conceitos de rede',
      question:
        'Qual rede é mais suscetível a variações de latência por depender de múltiplos provedores?',
      options: ['LAN', 'WAN', 'PAN', 'Rede de laboratório isolada'],
      answer: 'WAN',
      clue: 'WAN depende de infraestruturas externas.',
    },
    {
      num: 25,
      tropic: '1. Network Fundamentals',
      subTropic: '1.1 Conceitos de rede',
      question: 'Qual cenário caracteriza melhor uma MAN corporativa?',
      options: [
        'Rede de um único andar',
        'Rede entre matriz e filial em outro país',
        'Rede entre prédios na mesma cidade',
        'Conexão Bluetooth entre dispositivos',
      ],
      answer: 'Rede entre prédios na mesma cidade',
      clue: 'Mesmo município, escala metropolitana.',
    },

    {
      num: 26,
      tropic: '1. Network Fundamentals',
      subTropic: '1.1 Conceitos de rede',
      question:
        'Qual tipo de rede geralmente apresenta maior controle administrativo interno?',
      options: [
        'WAN pública',
        'LAN corporativa',
        'Internet global',
        'Backbone internacional',
      ],
      answer: 'LAN corporativa',
      clue: 'Totalmente gerenciada pela organização.',
    },
    {
      num: 27,
      tropic: '1. Network Fundamentals',
      subTropic: '1.1 Conceitos de rede',
      question:
        'Uma conexão via link satelital entre continentes é classificada como:',
      options: ['LAN', 'MAN', 'WAN', 'PAN'],
      answer: 'WAN',
      clue: 'Longa distância geográfica.',
    },
    {
      num: 28,
      tropic: '1. Network Fundamentals',
      subTropic: '1.1 Conceitos de rede',
      question: 'Qual rede normalmente apresenta menor latência?',
      options: [
        'WAN internacional',
        'Link satelital',
        'LAN local',
        'Rede intercontinental',
      ],
      answer: 'LAN local',
      clue: 'Menor distância, menor latência.',
    },
    {
      num: 29,
      tropic: '1. Network Fundamentals',
      subTropic: '1.1 Conceitos de rede',
      question: 'Qual opção descreve corretamente uma PAN?',
      options: [
        'Rede que cobre um país',
        'Rede metropolitana de fibra',
        'Rede pessoal de curto alcance',
        'Rede corporativa global',
      ],
      answer: 'Rede pessoal de curto alcance',
      clue: 'PAN é pessoal e limitada em alcance.',
    },
    {
      num: 30,
      tropic: '1. Network Fundamentals',
      subTropic: '1.1 Conceitos de rede',
      question:
        'Uma empresa possui duas salas no mesmo prédio conectadas por switches. Mesmo havendo dois ambientes físicos distintos, a rede ainda é classificada como:',
      options: ['MAN', 'WAN', 'LAN', 'PAN'],
      answer: 'LAN',
      clue: 'Ainda é rede local dentro do mesmo prédio.',
    },
    {
      num: 1,
      tropic: '1. Network Fundamentals',
      subTropic: '1.2 Topologias e dispositivos avançados',
      question:
        'Uma empresa possui três filiais em diferentes cidades. Cada filial tem uma LAN local conectada a um roteador, e todos os roteadores se conectam a um provedor MPLS. Qual é a topologia WAN utilizada?',
      options: ['Malha parcial', 'Estrela', 'Anel', 'Barramento'],
      answer: 'Estrela',
      clue: 'Todos os roteadores conectam a um ponto central (provedor).',
    },
    {
      num: 2,
      tropic: '1. Network Fundamentals',
      subTropic: '1.2 Topologias e dispositivos avançados',
      question:
        'Em uma MAN que conecta vários prédios de um campus universitário, qual dispositivo é mais crítico para gerenciar o tráfego entre os prédios?',
      options: ['Switch de acesso', 'Roteador', 'Hub', 'Access Point'],
      answer: 'Roteador',
      clue: 'Roteadores gerenciam sub-redes e tráfego entre redes diferentes, mesmo dentro de uma MAN.',
    },
    {
      num: 3,
      tropic: '1. Network Fundamentals',
      subTropic: '1.2 Topologias e dispositivos avançados',
      question:
        'Um administrador deseja isolar o tráfego de VoIP do restante da rede local (LAN) usando VLANs. Qual dispositivo é essencial para implementar isso?',
      options: [
        'Switch Layer 2',
        'Switch Layer 3',
        'Roteador',
        'Firewall de perímetro',
      ],
      answer: 'Switch Layer 3',
      clue: 'Switch L3 permite segmentação de rede com roteamento interno, fundamental para VLANs.',
    },
    {
      num: 4,
      tropic: '1. Network Fundamentals',
      subTropic: '1.2 Topologias e dispositivos avançados',
      question:
        'Qual característica diferencia uma WAN MPLS de uma WAN baseada em VPN sobre Internet pública?',
      options: [
        'MPLS é sempre sem fio',
        'MPLS fornece garantia de SLA e prioridade de tráfego',
        'VPN não criptografa os dados',
        'MPLS é usada apenas para redes domésticas',
      ],
      answer: 'MPLS fornece garantia de SLA e prioridade de tráfego',
      clue: 'MPLS permite QoS, VPN depende de Internet pública sem garantia de SLA.',
    },
    {
      num: 5,
      tropic: '1. Network Fundamentals',
      subTropic: '1.2 Topologias e dispositivos avançados',
      question:
        'Em um cenário de WAN corporativa, qual é a principal responsabilidade do administrador de rede?',
      options: [
        'Gerenciar apenas cabos dentro do prédio',
        'Configurar roteadores, VPNs e monitorar links WAN',
        'Instalar impressoras em LANs',
        'Gerenciar contas de e-mail dos usuários',
      ],
      answer: 'Configurar roteadores, VPNs e monitorar links WAN',
      clue: 'WAN exige configuração de roteadores, monitoramento e políticas de conectividade.',
    },
    {
      num: 6,
      tropic: '1. Network Fundamentals',
      subTropic: '1.2 Topologias e dispositivos avançados',
      question:
        'Uma rede corporativa tem LAN em dois prédios e precisa de alta disponibilidade entre eles. Qual topologia física de conexão entre os prédios aumenta a redundância?',
      options: ['Estrela simples', 'Anel', 'Barramento único', 'Conexão PAN'],
      answer: 'Anel',
      clue: 'Anel permite caminho alternativo se um link falhar.',
    },
    {
      num: 7,
      tropic: '1. Network Fundamentals',
      subTropic: '1.2 Topologias e dispositivos avançados',
      question:
        'Em uma LAN corporativa, qual dispositivo é responsável por segmentar domínios de colisão e reduzir broadcast?',
      options: ['Hub', 'Switch', 'Access Point', 'Roteador'],
      answer: 'Switch',
      clue: 'Switch segmenta domínios de colisão, diferente de roteadores que segmentam sub-redes.',
    },
    {
      num: 8,
      tropic: '1. Network Fundamentals',
      subTropic: '1.2 Topologias e dispositivos avançados',
      question:
        'Qual combinação de redes permite que uma filial em outra cidade funcione como extensão da LAN corporativa, mantendo políticas internas e segurança?',
      options: [
        'LAN local + VPN WAN',
        'MAN + PAN',
        'PAN + Internet pública sem criptografia',
        'WAN pública sem controle',
      ],
      answer: 'LAN local + VPN WAN',
      clue: 'VPN permite extensão segura da LAN sobre WAN.',
    },
    {
      num: 9,
      tropic: '1. Network Fundamentals',
      subTropic: '1.2 Topologias e dispositivos avançados',
      question:
        'Em um campus universitário com MAN, switches L2 conectam prédios e roteadores interligam sub-redes. Qual pegadinha clássica a prova pode usar aqui?',
      options: [
        'Confundir LAN com MAN',
        'Confundir roteador com firewall',
        'Confundir Wi-Fi com PAN',
        'Confundir IP público com MAC address',
      ],
      answer: 'Confundir LAN com MAN',
      clue: 'A MAN interliga várias LANs, mas cada prédio ainda tem sua LAN interna.',
    },
    {
      num: 10,
      tropic: '1. Network Fundamentals',
      subTropic: '1.2 Topologias e dispositivos avançados',
      question:
        'Uma empresa deseja priorizar tráfego de ERP sobre a rede WAN corporativa. Qual dispositivo e recurso devem ser configurados?',
      options: [
        'Switch Layer 2 com VLANs',
        'Roteador com QoS',
        'Hub com cabos CAT5',
        'Access Point com SSID aberto',
      ],
      answer: 'Roteador com QoS',
      clue: 'QoS no roteador WAN permite priorizar tráfego crítico entre filiais.',
    },
  ];
}
