function loadQuestions02() {
  return [
    {
      num: 1,
      question: 'Uma empresa utiliza um switch central conectando todos os computadores. Se o switch falhar, toda a rede para. Essa topologia é:',
      options: ['Malha completa', 'Estrela', 'Barramento', 'Anel'],
      answer: 'Estrela',
      clue: 'Topologia estrela possui ponto central que pode ser ponto único de falha.',
    },
    {
      num: 2,
      question: 'Qual característica é típica de uma topologia em malha completa?',
      options: [
        'Baixo custo e baixa redundância',
        'Alta redundância e alto custo',
        'Um único cabo compartilhado',
        'Dependência de um hub central',
      ],
      answer: 'Alta redundância e alto custo',
      clue: 'Malha completa conecta todos os nós entre si.',
    },
    {
      num: 3,
      question: 'Uma rede antiga utiliza um único cabo coaxial compartilhado por todos os dispositivos. Isso representa qual topologia?',
      options: ['Estrela', 'Malha', 'Barramento', 'Árvore'],
      answer: 'Barramento',
      clue: 'Barramento utiliza um único meio compartilhado.',
    },
    {
      num: 4,
      question: 'Qual topologia oferece maior tolerância a falhas em ambiente crítico?',
      options: ['Barramento', 'Estrela simples', 'Malha completa', 'Topologia linear'],
      answer: 'Malha completa',
      clue: 'Múltiplos caminhos evitam interrupção total.',
    },
    {
      num: 5,
      question: 'Em uma topologia estrela, se um cabo de um computador for desconectado, o que acontece?',
      options: [
        'Toda a rede falha',
        'Apenas aquele dispositivo perde conexão',
        'O switch é reiniciado',
        'Todos entram em loop',
      ],
      answer: 'Apenas aquele dispositivo perde conexão',
      clue: 'Falha individual não afeta os demais, diferente do barramento.',
    },
    {
      num: 6,
      question: 'Qual é a principal desvantagem da topologia barramento?',
      options: [
        'Alto custo',
        'Excesso de cabos',
        'Colisões e ponto único de falha no cabo principal',
        'Complexidade de configuração',
      ],
      answer: 'Colisões e ponto único de falha no cabo principal',
      clue: 'Se o cabo principal falhar, toda rede para.',
    },
    {
      num: 7,
      question: 'Uma empresa conecta todos os roteadores entre si para garantir múltiplos caminhos. Isso caracteriza:',
      options: ['Estrela', 'Barramento', 'Malha', 'Topologia física linear'],
      answer: 'Malha',
      clue: 'Todos os dispositivos possuem múltiplas conexões.',
    },
    {
      num: 8,
      question: 'Qual topologia normalmente apresenta melhor escalabilidade com switches modernos?',
      options: ['Barramento', 'Estrela', 'Malha completa doméstica', 'Coaxial compartilhado'],
      answer: 'Estrela',
      clue: 'Switch central facilita expansão.',
    },
    {
      num: 9,
      question: 'Em comparação com malha completa, a topologia estrela geralmente:',
      options: [
        'Tem maior redundância',
        'É mais cara',
        'Tem menor custo e menor redundância',
        'Não utiliza switches',
      ],
      answer: 'Tem menor custo e menor redundância',
      clue: 'Estrela depende do dispositivo central.',
    },
    {
      num: 10,
      question: 'Qual cenário melhor representa uma malha parcial?',
      options: [
        'Todos os dispositivos conectados entre si',
        'Alguns dispositivos possuem múltiplos caminhos',
        'Um único cabo compartilhado',
        'Um hub conectando todos os PCs',
      ],
      answer: 'Alguns dispositivos possuem múltiplos caminhos',
      clue: 'Malha parcial não conecta todos a todos.',
    },
    {
      num: 11,
      question: 'Qual topologia foi amplamente utilizada em redes Ethernet antigas com hubs?',
      options: ['Barramento lógico', 'Malha física', 'Anel token', 'Malha completa'],
      answer: 'Barramento lógico',
      clue: 'Hubs operavam como meio compartilhado, semelhante ao barramento.',
    },
    {
      num: 12,
      question: 'Se o cabo principal for rompido em uma rede barramento, o impacto será:',
      options: [
        'Nenhum',
        'Apenas um host desconecta',
        'Toda a rede é afetada',
        'Apenas o roteador falha',
      ],
      answer: 'Toda a rede é afetada',
      clue: 'O cabo principal é único ponto de falha.',
    },
    {
      num: 13,
      question: 'Qual topologia é mais comum em redes LAN modernas?',
      options: ['Barramento coaxial', 'Estrela com switches', 'Malha completa doméstica', 'Anel físico'],
      answer: 'Estrela com switches',
      clue: 'Redes Ethernet atuais usam estrela física.',
    },
    {
      num: 14,
      question: 'Uma topologia malha completa entre 5 roteadores exige quantas conexões diretas por roteador?',
      options: ['1', '2', '4', '5'],
      answer: '4',
      clue: 'Cada roteador conecta aos outros quatro.',
    },
    {
      num: 15,
      question: 'Qual topologia apresenta maior custo de cabeamento?',
      options: ['Barramento', 'Estrela simples', 'Malha completa', 'Árvore básica'],
      answer: 'Malha completa',
      clue: 'Número de links cresce exponencialmente.',
    },
    {
      num: 16,
      question: 'Qual característica pode ser considerada vantagem da estrela sobre barramento?',
      options: [
        'Menor uso de cabos',
        'Maior isolamento de falhas',
        'Uso exclusivo de coaxial',
        'Ausência de switch',
      ],
      answer: 'Maior isolamento de falhas',
      clue: 'Falha de um cabo não derruba toda rede.',
    },
    {
      num: 17,
      question: 'Qual topologia física é mais associada a ambientes de backbone crítico?',
      options: ['Barramento', 'Malha parcial ou completa', 'Hub central único', 'Topologia linear simples'],
      answer: 'Malha parcial ou completa',
      clue: 'Backbones exigem redundância.',
    },
    {
      num: 18,
      question: 'Em termos de desempenho, qual topologia antiga sofria mais com colisões?',
      options: ['Malha', 'Estrela com switch', 'Barramento', 'Árvore estruturada'],
      answer: 'Barramento',
      clue: 'Meio compartilhado aumenta colisões.',
    },
    {
      num: 19,
      question: 'Qual topologia reduz drasticamente colisões ao usar switches?',
      options: ['Estrela moderna', 'Barramento coaxial', 'Malha passiva', 'Topologia linear'],
      answer: 'Estrela moderna',
      clue: 'Switch segmenta domínio de colisão.',
    },
    {
      num: 20,
      question: 'Se uma empresa deseja máxima disponibilidade, qual topologia é mais indicada?',
      options: ['Barramento', 'Estrela simples', 'Malha completa', 'Cadeia linear'],
      answer: 'Malha completa',
      clue: 'Redundância elimina ponto único de falha.',
    },
    {
      num: 21,
      question: 'Qual topologia possui um único meio físico compartilhado por todos?',
      options: ['Estrela', 'Malha', 'Barramento', 'Árvore'],
      answer: 'Barramento',
      clue: 'Todos compartilham o mesmo cabo.',
    },
    {
      num: 22,
      question: 'Uma rede com switch central e links redundantes para outro switch caracteriza:',
      options: ['Barramento puro', 'Malha parcial', 'Estrela simples', 'Rede linear'],
      answer: 'Malha parcial',
      clue: 'Há redundância, mas não total.',
    },
    {
      num: 23,
      question: 'Qual topologia apresenta maior complexidade de gerenciamento?',
      options: ['Barramento', 'Estrela básica', 'Malha completa', 'Topologia simples'],
      answer: 'Malha completa',
      clue: 'Grande número de conexões exige mais controle.',
    },
    {
      num: 24,
      question: 'Qual cenário demonstra ponto único de falha típico?',
      options: [
        'Malha completa',
        'Estrela com switch único',
        'Malha parcial com redundância',
        'Rede com múltiplos caminhos',
      ],
      answer: 'Estrela com switch único',
      clue: 'Falha no switch central derruba a rede.',
    },
    {
      num: 25,
      question: 'Qual topologia tende a ser menos utilizada atualmente em redes corporativas modernas?',
      options: ['Estrela', 'Malha parcial', 'Barramento coaxial', 'Topologia hierárquica'],
      answer: 'Barramento coaxial',
      clue: 'Tecnologia antiga baseada em cabo único.',
    },
    {
      num: 26,
      question: 'Uma topologia estrela pode se tornar altamente disponível se:',
      options: [
        'Remover o switch central',
        'Adicionar redundância e múltiplos switches',
        'Usar apenas cabo coaxial',
        'Eliminar roteadores',
      ],
      answer: 'Adicionar redundância e múltiplos switches',
      clue: 'Redundância reduz ponto único de falha.',
    },
    {
      num: 27,
      question: 'Qual topologia cresce mais rapidamente em número de links conforme novos dispositivos são adicionados?',
      options: ['Barramento', 'Estrela', 'Malha completa', 'Linear'],
      answer: 'Malha completa',
      clue: 'Número de conexões cresce exponencialmente.',
    },
    {
      num: 28,
      question: 'Em termos práticos, redes LAN modernas usam qual topologia física predominante?',
      options: ['Barramento físico', 'Estrela física', 'Malha completa obrigatória', 'Cadeia coaxial'],
      answer: 'Estrela física',
      clue: 'Switch centraliza conexões.',
    },
    {
      num: 29,
      question: 'Qual topologia oferece maior custo-benefício para pequenas empresas?',
      options: ['Malha completa', 'Barramento antigo', 'Estrela com switch', 'Malha total com 10 links'],
      answer: 'Estrela com switch',
      clue: 'Equilíbrio entre custo e eficiência.',
    },
    {
      num: 30,
      question: 'Se a questão mencionar “alta redundância e múltiplos caminhos alternativos”, provavelmente está se referindo a qual topologia?',
      options: ['Barramento', 'Estrela simples', 'Malha', 'Topologia linear'],
      answer: 'Malha',
      clue: 'Múltiplos caminhos são característica da malha.',
    },
  ];
 }
